# .github/workflows/prod.yml
name: Production deploy

on:
  push:
    branches:
      - master   # change if your production branch has a different name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present

      - name: Deploy to Netlify
        # Using the widely used actions-netlify action
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'        # <-- change to './build' if your project uses CRA
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions (main)"
        env:
          NETLIFY_AUTH_TOKEN: nfp_siWuAYHEseyUgkQfzHRWjwJ8i17F4vhpea70 # netlify token with write permissions
          NETLIFY_SITE_ID: fba7bf71-b910-4dd6-a031-64f46e2ad8bf # site id
